### PR TITLE
add BHist, enhance usability

### PR DESCRIPTION
**Pull request by francescoalemanno**

### CODE REVIEW

**Comment by Moelf** [comment]
so, very sadly `StatsBase` histograms don't have errors

**Comment by francescoalemanno** [comment]
> so, very sadly `StatsBase` histograms don't have errors

Right... This morning I was looking for a package offering "AbstractHistogram". I decided to conjure `BHist` as soon as I discovered that the package was indeed StatsBase...

**Comment by Moelf** [comment]
yeah, `FHist.jl` does it because I was stupid.

**Comment by francescoalemanno** [comment]
> yeah, `FHist.jl` does it because I was stupid.

We could be the first brave heroes to publish "AbstractStats.jl". What do you think? 
Ideally this package should end up in JuliaStats

**Comment by Moelf** [comment]
my ability probably is limited to AbstractHistograms

**Comment by francescoalemanno** [comment]
I agree

**Pull request merged**
